- name: Install ZSH (Fedora)
  dnf:
    name: zsh
    state: latest
  become: yes
  when: ansible_distribution == "Fedora"

- name: Symlink ~/.zprezto
  file:
    src: "{{ ansible_env.HOME }}/dotfiles/src/prezto"
    dest: "{{ ansible_env.HOME }}/.zprezto"
    state: link

- name: Get Prezto runcoms from dotfiles
  shell: ls ~/.zprezto/runcoms | grep -v README.md
  register: prezto_runcoms

- name: Symlink Prezto runcoms
  file:
    src: "{{ ansible_env.HOME }}/.zprezto/runcoms/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.{{ item }}"
    state: link
  with_items: "{{ prezto_runcoms.stdout_lines }}"

- name: Get zsh install location
  shell: command -v zsh
  register: zsh_location

- name: Add zsh to /etc/shells
  lineinfile:
    dest: /etc/shells
    line: "{{ item }}"
    state: present
  with_items: "{{ zsh_location.stdout_lines }}"
  become: yes

- name: Make zsh default shell for current user
  user: 
    name: "{{ ansible_env.USER }}"
    shell: "{{ item }}"
  with_items: "{{ zsh_location.stdout_lines }}"
  become: yes