- name: Clone rbenv repo
  git:
    repo: "{{ rbenv_repo }}"
    dest: "{{ ansible_env.HOME }}/.rbenv"
    clone: yes

- name: Configure dynamic bash completion
  command: src/configure
  args:
    chdir: "{{ ansible_env.HOME }}/.rbenv"
  ignore_errors: yes

- name: Attempt to build dynamic bash completion
  command: make -C src
  args:
    chdir: "{{ ansible_env.HOME }}/.rbenv"
  ignore_errors: yes

- name: Add rbenv to path
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: "export PATH=\"$HOME/.rbenv/bin:$PATH\""
    state: present

- name: Setup rbenv in shell
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: "eval \"$(rbenv init -)\""
    state: present