- name: Clone rbenv repo
  git:
    repo: "{{ rbenv_repo }}"
    dest: "{{ ansible_env.HOME }}/.rbenv"
    clone: yes

- name: Configure dynamic bash completion
  command: src/configure
  args:
    chdir: "{{ ansible_env.HOME }}/.rbenv"
  ignore_errors: yes

- name: Attempt to build dynamic bash completion
  command: make -C src
  args:
    chdir: "{{ ansible_env.HOME }}/.rbenv"
  ignore_errors: yes